### PR TITLE
FT2-9 Alternate route frontend

### PR DESCRIPTION
**Pull request by daphneaugier**
- The alternative (ALT) button is clickable to display all the alternative routes 
- The different alternatives are clickable and it changes the route on the map
- The different paths are displayed on the map, the chosen one is red, the other(s) is/are dotted in grey

### CODE REVIEW

**Comment by daphneaugier** [comment]
> The outlines of the building are no longer there. The auto complete searching fields does not appear and the destination seems to be hard coded, as I am not able to change to a different route, which is on submaster currently.
> Github says there are some conflicts as well.
> The alternative routes works and looks pretty on the map!

Thank you for your review. Effectively, I didn't pull the submaster often... Fixing the merging

**Comment by daphneaugier** [comment]
I had a lot of issues after the pull from the submaster. It took me a while to re-understand what has been done by my teammates in the meantime so that my work would fit the new changes.

**Comment by yabdelkawy** [comment]
So I found some bugs 

**Bug One**

- [ ] Enter in your destination and hit the route button

- [ ] Click on one of the transportation modes besides the default car one

- [ ] Click on the alt button

- [ ] You'll see a list of all the alts including the ones from the previous transportation mode. 
Screenshot_1585444252

- [ ] If you click on the box, the old list disappears and the car button is on even though the transportation method wasn't changed.
Screenshot_1585444256

**Bug Two**

- [ ] Enter in your destination and hit the route button

- [ ] Click on one of the transportation modes besides the default car one

- [ ] Click on the alt button

- [ ] Select an alt route

- [ ] Click the directions button. The button for car is suddenly on even though the transportation mode has not been changed. 
Screenshot_1585445136





One of the reasons this bug is here is partially due to the way I coded the transportation mode. As soon as the direction fragment is called, the car button is checked by default. If you're recalling the directions fragment after the button is clicked, the car button will be checked and the other buttons will be unchecked.

**Comment by daphneaugier** [comment]
> So I found some bugs
> 
> **Bug One**
> 
> * [ ]  Enter in your destination and hit the route button
> * [ ]  Click on one of the transportation modes besides the default car one
> * [ ]  Click on the alt button
> * [ ]  You'll see a list of all the alts including the ones from the previous transportation mode.
> * [ ]  If you click on the box, the old list disappears. Sometimes, the car button comes on even though the transportation method wasn't changed, though that secondary bug appears to be tempermental
> 
> **Bug Two**
> 
> * [ ]  Enter in your destination and hit the route button
> * [ ]  Click on one of the transportation modes besides the default car one
> * [ ]  Click on the alt button
> * [ ]  Select an alt route
> * [ ]  Click the directions button. The button for car is suddenly on even though the transportation mode has not been changed.
> 
> One of the reasons this bug is here is partially due to the way I coded the transportation mode. As soon as the direction fragment is called, the car button is checked by default. If you're recalling the directions fragment after the button is clicked, the car button will be checked and the other buttons will be unchecked.

Thank you for your detailed review! I will work on that and keep you updated

**Pull request merged**
