### PR TITLE
Def 10 missing location message

### PR DESCRIPTION
**Pull request by johnstonstott**
Contains functionality to display a toast when a) the location permission of the **application** was denied, or b) the **device** location is disabled. 

Please check the following:

a) Location permission message
1) Uninstall the app or remove location permission from the app
2) Reinstall/open the app again, you should see the prompt to let ConUMap access your location (this is what happens on phone, I'm not sure what it's like for the emulator)

* If you press Deny, a message should appear saying "Can't locate because location permission was denied."
* If after denying, you attempt to press the "locate user" button, the same message should appear
* If you press Allow, it should immediately focus the map on your location (it didn't used to do this immediately after accepting permission! Used to only do it on app open AFTER permission was already accepted)

b) Device location message -- you can test this with the location permission already accepted
1) Turn off device location
2) Open application
* If you open the app with location of device turned off, a message should say "Can't locate because device location is turned off." and it will not move the map.
* If you attempt to press the "locate user" button, and device location is disabled, the same message should appear

For b), would be great if we could have approval from phone and emulator. The way of checking if device location is on is different for different versions of Android, so if we could check that it works on both >API 23 (newer than Marshmallow) and <=API 23 (Marshmallow and older), would be great. In addition, feel free to try toggling the device location while the app is open to see if it works.

### CODE REVIEW

**Comment by Andynism** [comment]
I'll check this PR later, the emulator is trying to kill my computer.

**Comment by johnstonstott** [comment]
> 
> 
> My app keeps crashing, i get this error on this branch:
> image

I think I know what's causing it, I will take a look later. Thanks for bringing it to my attention

**Comment by johnstonstott** [comment]
Thanks for your review @yabdelkawy !

For your Part A review, there is only 2 options for toast display length and it is set to the longer one. There is a way to make it show for longer (essentially displaying the same toast twice in a row) but it's not great so I tried to make the message short. I will ask for the opinion of @Andynism and @MaelSemler and if you all agree that it goes away too fast I can make it longer.

For part B, do you mean the blue circle to show your position is missing? I just want to confirm that this is what you mean by the marker.

Thank you!

**Comment by MaelSemler** [comment]
For part A everything works fine on the emulator API 29, good job!
For part B, i have the same bug that Yomna has, which is the blue circle which indicates the position is missing after doing the steps she said in the previous comment

**Comment by yabdelkawy** [comment]
@johnstonstott Yup, that's exactly what I meant! 

**Running Part B on emulator Android R** 
I found another bug. 
- [ ]  Have your phone's location permission on
- [ ]  Turn off your app's location permission
- [ ]  Go into the application
- [ ] Exit application and turn app's location permission on
- [ ] Go into application and click the locating button. The button won't work and the location is never determined. The toast doesn't show either meaning that the location permission is enabled but something isn't right.
image

**Comment by johnstonstott** [comment]
Latest commit should correct the issue where the "I am here" dot disappeared after toggling location. From what I've tested, when returning to the app, it will move to you on the map right away but it may take a few seconds for the dot to reappear. However, it should reappear eventually on its own. This doesn't seem to be something within my control.

@yabdelkawy, for the second bug you found, I was not able to duplicate it on my end (Mobile, Android 10). However, my other bug fix changed the way the app behaves when the user leaves it and returns. This may fix the issue you are having. 

Lastly, @MaelSemler and @Andynism please let me know the verdict for the length of the toast -- do you think it's too short for the message?

Thanks everyone and please let me know so we can wrap this up!

**Comment by MaelSemler** [comment]
I feel like the Toast length was long enough so that I could read the entire message.

**Comment by yabdelkawy** [comment]
I’ll check the PR first thing tomorrow. My emulator just paralyzed my laptop, so sorry for the late review!

**Comment by yabdelkawy** [comment]
For Part B (Tested with emulators running on API 23 and Android R) 

- Concerning the first bug with the missing location markers, I still can't see them on either emulator but if Mael can see them then it should be okay. Since this is something not within your control, I'll approve the request. 
- Concerning the second bug where the location button does not work, it works perfectly for me! 
Thanks Johnston!

**Pull request merged**
