### PR TITLE
Ft3 7 directions to next class

### PR DESCRIPTION
**Pull request by lposo**
When you have the location for an event in the CalendarScheduleFragment and you hit the "Go Now" button, you should be brought to the SearchCompletedFragment, where you can then get the directions for the next class. Uses code from Yomna's branch so it shouldn't be merged until her pull request is done.

### CODE REVIEW

**Comment by yabdelkawy** [comment]
I don't believe I can access my schedule even after logging in to Google. Here are some screenshots of what I'm getting: 
Screenshot_1587299830
And this is after I click my name/email.
Screenshot_1587299834

**Comment by lposo** [comment]
Oh, David posted a link in the general channel on how to fix that. You need to send him your SHA1 so that you can run the calendar.

**Comment by lposo** [comment]
Do you know exactly what error was thrown?

**Comment by lposo** [comment]
That's weird... this is what I set as the event I'm trying to get to:
Screenshot_20200419-124512_Calendar 1

**Comment by lposo** [comment]
I modified the "Go Now" button so it shouldn't crash if the event location is not set. But I don't know why the getLocationFromAddress function is returning a null value.

**Comment by lposo** [comment]
Added another fix so that if the event location was not a valid address (like say it was just the word "Concrete") the "Go Now" button wouldn't work.

**Comment by MaelSemler** [comment]
The app still crashes for me, even when I have a location which is valid.

**Comment by lposo** [comment]
I changed a variable in the getLocationFromAddress from val to var, could you add a break point in the getLocationFromAddress function and tell me what is the value of address after the line`address = coder.getFromLocationName(strAddress, 1)` is called?

**Pull request merged**
