### PR TITLE
1 5 buildings

### PR DESCRIPTION
**Pull request by lposo**
Added creation of building shapes in the setUpMap() method.

### CODE REVIEW

**Comment by lposo** [comment]
I made the borders to have a width of 0.1 pixels so they appear to be invisible.

**Comment by johnstonstott** [comment]
In response to @Andynism, I just had the same issue in my branch but with the building markers instead. In the `changeBetweenCampuses` function, there is a `map.clear` which removed the markers I added. I imagine the same is happening here with the building outlines. See https://github.com/MaelSemler/mini-cap/pull/70/files#r386076799 for more info and what I did to fix it.

**Comment by lposo** [comment]
I followed what you did @johnstonstott and was able to get them to appear when hitting the SGW/LOY buttons. But for some reason, the map itself is blank now.

**Comment by lposo** [comment]
Resolved the merge conflicts, if it's working for you guys then I guess it's fine. I'll try to figure out why m it's not working on my end.

**Pull request merged**
