### PR TITLE
System and Unit tests for the calendar feature FT3-1...6

### PR DESCRIPTION
**Pull request by DavSemu**
System and Unit tests for the calendar features  FT3-1 to FT3-6.
The system tests will only work if a google account is already signed in.

### CODE REVIEW

**Comment by MaelSemler** [comment]
For some reason  I get that error 
image

**Comment by Andynism** [comment]
I'm having issues signing in with my Google Account, so the calendar tests failing for me.

**Comment by johnstonstott** [comment]
Update: All unit tests pass except for DirectionServiceTest, if I comment it out all the remaining unit tests work as intended.

**Comment by DavSemu** [comment]
The was an issue with the "DirectionsTextBox". It wasn't in the view anymore because of the new popup window. The tests were modified and the issue was addressed.

**Pull request merged**
