### PR TITLE
DEV-12-shuttle-bus

### PR DESCRIPTION
**Pull request by daphneaugier**
The shuttle bus path is available under the radio button of the bus as it is considered as a kind of public transport. Its path is drawn in red like the other alternate paths when the alternate option is clicked. We can select it in the list of paths, it is displayed as followed : 
Capture d’écran 2020-04-18 à 18 50 40

**HOWEVER** I was running out of resources and time to figure out how to make the shuttle bus time-aware. Even if I inputted the schedules of the shuttle bus into a .xml file, I couldn't not find a way to retrieve the different times.

### CODE REVIEW

**Comment by daphneaugier** [comment]
From the requirements list for meeting it says :

 2.f) Support for the Concordia Shuttle Service (time-aware and location-aware)

**Comment by daphneaugier** [comment]
> The ChangeDestinationTest appears to be failing for me. The problem seems to originate from the Directions fragment. Could you double check if the tests are working on your side?
> 
> Screenshot 2020-04-18 19 46 02

This test passes on my computer : 

Capture d’écran 2020-04-18 à 20 07 56

**Comment by Andynism** [comment]
There's a problem with the geocoder being used in the Directions fragment on my end, so I'll withdraw my review for now.

**Comment by johnstonstott** [comment]
I am able to get the same as your screenshot, please resolve the conflicts so I can rereview

**Comment by johnstonstott** [comment]
Are you sure you pulled submaster with all the other PRs merged? There are some things that were patched today that are no longer working on your branch

**Pull request merged**
